// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: tcg_data.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardId        string                 `protobuf:"bytes,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardRequest) Reset() {
	*x = CardRequest{}
	mi := &file_tcg_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardRequest) ProtoMessage() {}

func (x *CardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tcg_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardRequest.ProtoReflect.Descriptor instead.
func (*CardRequest) Descriptor() ([]byte, []int) {
	return file_tcg_data_proto_rawDescGZIP(), []int{0}
}

func (x *CardRequest) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

type CardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,3,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	SetName       string                 `protobuf:"bytes,4,opt,name=set_name,json=setName,proto3" json:"set_name,omitempty"`
	Success       bool                   `protobuf:"varint,5,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardResponse) Reset() {
	*x = CardResponse{}
	mi := &file_tcg_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardResponse) ProtoMessage() {}

func (x *CardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tcg_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardResponse.ProtoReflect.Descriptor instead.
func (*CardResponse) Descriptor() ([]byte, []int) {
	return file_tcg_data_proto_rawDescGZIP(), []int{1}
}

func (x *CardResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CardResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CardResponse) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *CardResponse) GetSetName() string {
	if x != nil {
		return x.SetName
	}
	return ""
}

func (x *CardResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_tcg_data_proto protoreflect.FileDescriptor

const file_tcg_data_proto_rawDesc = "" +
	"\n" +
	"\x0etcg_data.proto\x12\ttcgworker\"&\n" +
	"\vCardRequest\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\tR\x06cardId\"\x84\x01\n" +
	"\fCardResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\timage_url\x18\x03 \x01(\tR\bimageUrl\x12\x19\n" +
	"\bset_name\x18\x04 \x01(\tR\asetName\x12\x18\n" +
	"\asuccess\x18\x05 \x01(\bR\asuccess2S\n" +
	"\x0eTcgDataService\x12A\n" +
	"\x0eGetPokemonCard\x12\x16.tcgworker.CardRequest\x1a\x17.tcgworker.CardResponseB'\n" +
	"\x15com.poketlin.api.grpcP\x01Z\fworker-go/pbb\x06proto3"

var (
	file_tcg_data_proto_rawDescOnce sync.Once
	file_tcg_data_proto_rawDescData []byte
)

func file_tcg_data_proto_rawDescGZIP() []byte {
	file_tcg_data_proto_rawDescOnce.Do(func() {
		file_tcg_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tcg_data_proto_rawDesc), len(file_tcg_data_proto_rawDesc)))
	})
	return file_tcg_data_proto_rawDescData
}

var file_tcg_data_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_tcg_data_proto_goTypes = []any{
	(*CardRequest)(nil),  // 0: tcgworker.CardRequest
	(*CardResponse)(nil), // 1: tcgworker.CardResponse
}
var file_tcg_data_proto_depIdxs = []int32{
	0, // 0: tcgworker.TcgDataService.GetPokemonCard:input_type -> tcgworker.CardRequest
	1, // 1: tcgworker.TcgDataService.GetPokemonCard:output_type -> tcgworker.CardResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tcg_data_proto_init() }
func file_tcg_data_proto_init() {
	if File_tcg_data_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tcg_data_proto_rawDesc), len(file_tcg_data_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tcg_data_proto_goTypes,
		DependencyIndexes: file_tcg_data_proto_depIdxs,
		MessageInfos:      file_tcg_data_proto_msgTypes,
	}.Build()
	File_tcg_data_proto = out.File
	file_tcg_data_proto_goTypes = nil
	file_tcg_data_proto_depIdxs = nil
}
