// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: tcg_data.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TcgDataService_GetPokemonCard_FullMethodName = "/tcgworker.TcgDataService/GetPokemonCard"
)

// TcgDataServiceClient is the client API for TcgDataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TcgDataServiceClient interface {
	GetPokemonCard(ctx context.Context, in *CardRequest, opts ...grpc.CallOption) (*CardResponse, error)
}

type tcgDataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTcgDataServiceClient(cc grpc.ClientConnInterface) TcgDataServiceClient {
	return &tcgDataServiceClient{cc}
}

func (c *tcgDataServiceClient) GetPokemonCard(ctx context.Context, in *CardRequest, opts ...grpc.CallOption) (*CardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CardResponse)
	err := c.cc.Invoke(ctx, TcgDataService_GetPokemonCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TcgDataServiceServer is the server API for TcgDataService service.
// All implementations must embed UnimplementedTcgDataServiceServer
// for forward compatibility.
type TcgDataServiceServer interface {
	GetPokemonCard(context.Context, *CardRequest) (*CardResponse, error)
	mustEmbedUnimplementedTcgDataServiceServer()
}

// UnimplementedTcgDataServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTcgDataServiceServer struct{}

func (UnimplementedTcgDataServiceServer) GetPokemonCard(context.Context, *CardRequest) (*CardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPokemonCard not implemented")
}
func (UnimplementedTcgDataServiceServer) mustEmbedUnimplementedTcgDataServiceServer() {}
func (UnimplementedTcgDataServiceServer) testEmbeddedByValue()                        {}

// UnsafeTcgDataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TcgDataServiceServer will
// result in compilation errors.
type UnsafeTcgDataServiceServer interface {
	mustEmbedUnimplementedTcgDataServiceServer()
}

func RegisterTcgDataServiceServer(s grpc.ServiceRegistrar, srv TcgDataServiceServer) {
	// If the following call panics, it indicates UnimplementedTcgDataServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TcgDataService_ServiceDesc, srv)
}

func _TcgDataService_GetPokemonCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TcgDataServiceServer).GetPokemonCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TcgDataService_GetPokemonCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TcgDataServiceServer).GetPokemonCard(ctx, req.(*CardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TcgDataService_ServiceDesc is the grpc.ServiceDesc for TcgDataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TcgDataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tcgworker.TcgDataService",
	HandlerType: (*TcgDataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPokemonCard",
			Handler:    _TcgDataService_GetPokemonCard_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tcg_data.proto",
}
