ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ ufrn.br.poketlin.api.ApplicationKt.module ]
    }

    poketlin {
    tcgdex {
        baseUrl = "https://api.tcgdex.net/v2"
        baseUrl = ${?TCGDEX_BASE_URL}
    }
}
}